- name: Build & Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: ubuntu
  tasks:
    - name: Stopping the Container
      docker_container:
        name: mico-container
        image: mico:latest
        state: stopped

    - name: Removing the Container
      docker_container:
        name: mico-container
        image: mico:latest
        state: absent

    - name: Removing a Docker Image
      docker_image:
        name: mico:latest
        state: absent
      
    - name: Building Docker Image
      docker_image:
        name: mico:latest
        source: build
        build:
          path: ~/project/
        state: present
      
    - name: Creating the Container
      docker_container:
        name: mico-container
        image: aadarshg619/mico:latest
        ports:
          - "80:80"
        state: started

